near/NEPs

text/0000-view-change-method.md, text/0018-view-change-method.md
A simple approach to improving and stabilizing the difference between view and change methods in contracts.
=> Improve view/change methods

specs/Economics/README.md
Fix up reward for accounting the max online threshold.
Adding more information for validator selection.
=> Update reward and validator selection sections

specs/RuntimeSpec/Receipts.md
Fix some typos in the `Receipts.md` file.
=> Fix language (typos) in Receipts.md

specs/Standards/FungibleToken/Core.md
=> fix typo wBTC -> wNEAR

specs/RuntimeSpec/Fees/Fees.md, specs/RuntimeSpec/FunctionCall.md
The goal is to document
- contract reward
- new DeleteAccount behaviour
- the process of charging fees inside Runtime
=> Update spec for DeleteAccount and FunctionCall

book.toml, specs/SUMMARY.md, specs/Standards/NonFungibleToken/Payout.md, specs/Standards/NonFungibleToken/README.md
Update from https://github.com/near/NEPs/pull/199
=> NFT Payout standard

specs/Standards/FungibleToken/Core.md, specs/Standards/NonFungibleToken/Core.md, specs/Standards/README.md
Also, solve https://github.com/near/NEPs/issues/214
=> doc(standards): fix links in Fungible & NonFungible Token

specs/Standards/NonFungibleToken/ApprovalManagement.md
Extra details about why approvals must be capped at a number determined by the contract author
=> standards/nft/approval: explain approval cap

specs/NetworkSpec/RoutingTableExchangeAlgorithm.md
Fix misspelling in `RoutingTableExchangeAlgorithm.md`.
=> Minor fixes to RoutingTableExchangeAlgorithm.md

specs/Standards/FungibleToken/Core.md, specs/Standards/NonFungibleToken/ApprovalManagement.md, specs/Standards/StorageManagement.md
=> Changed --amount 0.000..01 to --depositYocto 1

specs/Standards/README.md
=> Add events to contents in Standards section

specs/Standards/NonFungibleToken/Event.md
=> doc(nep171): use events NEP-297 inside NFT NEP-171

specs/SUMMARY.md, specs/Standards/FungibleToken/Event.md, specs/Standards/FungibleToken/README.md, specs/Standards/README.md
Closes #271
Please add here FT contract creators that you know
=> doc(nep141): add FT NEP-141 events section

specs/SUMMARY.md, specs/Standards/FungibleToken/Event.md, specs/Standards/FungibleToken/README.md, specs/Standards/NonFungibleToken/Event.md, specs/Standards/README.md
It was approved in #299 #300 , I accidentally merged them to the wrong branch
=> [duplicate #299 #300] Use NEP-297 in FT, NFT events section

specs/RuntimeSpec/FunctionCall.md, specs/RuntimeSpec/Preparation.md
I haven't had an opportunity to proof-read this yet, but I believe the description herein to be accurate.
Nits wrt writing style appreciated.
cc @matklad @bowenwang1996 @Ekleog @olonho @jakmeier 
(I ended up rolling the mostly reformatting changes to `FunctionCall` runtime spec into this while at this, lmk if you want this split out)
=> Add a RuntimeSpec for contract preparation

website/docusaurus.config.js, website/package.json, website/src/theme/SearchBar/algolia.css, website/src/theme/SearchBar/index.js, website/src/theme/SearchBar/lib/DocSearch.js, website/src/theme/SearchBar/lib/lunar-search.js, website/src/theme/SearchBar/lib/templates.js, website/src/theme/SearchBar/lib/utils.js, website/src/theme/SearchBar/styles.css, website/yarn.lock
Add a local search bar to Nomicon.io 
Note: we still want to get Algolia working across all our documentation sites, but we have been waiting for their support and meanwhile there's no search available.
=> Add Lunr local search bar

specs/GenesisConfig/GenesisConfig.md
Add documentation on genesis height that was previously missing.
=> fix: add genesis height documentation

specs/RuntimeSpec/Scenarios/FinancialTransaction.md
=> Fix minor typo

specs/RuntimeSpec/Receipts.md
=> fix: Fixed a typo in RuntimeSpec/Receipts.md

specs/RuntimeSpec/Transactions.md
=> took out extra bullet point from transactions.md spec

specs/Standards/Tokens/NonFungibleToken/Core.md
this was some work I had in progress on `master` a long time ago that I need to investigate
=> standards/NFT: previous_owner_id

specs/RuntimeSpec/Refunds.md
This PR adds a number of wording improvements in the Refunds section.
=> docs: Improve wording in Refunds

neps/nep-0001.md
=> doc: Fix confusing use of the phrase "subject matter experts"

nep-0000-template.md
We've recently proposed some improvements to NEP-0001 (#466). This template reflects those changes.
=> Update template to reflect NEP-0001

neps/nep-0001.md
We have made several changes to NEP-0001 (and the corresponding NEP-0000 template #467) to improve the clarity and effectiveness of the process. These changes include clarifying the roles and responsibilities and adding additional guidance for each step. We also reordered various sections to make it easier to read and navigate.
=> Updates to NEP-0001

neps/nep-0455.md
As it's been voted on and accepted
=> Update status of NEP-455 to Final

.markdownlint.json, README.md, neps/nep-0001.md, neps/nep-0021.md, neps/nep-0141.md, neps/nep-0145.md, neps/nep-0148.md, neps/nep-0171.md, neps/nep-0177.md, neps/nep-0178.md, neps/nep-0181.md, neps/nep-0199.md, neps/nep-0245.md, neps/nep-0297.md, neps/nep-0330.md, neps/nep-0364.md, neps/nep-0366.md, neps/nep-0399.md, neps/nep-0413.md, neps/nep-0418.md, neps/nep-0448.md, neps/nep-0455.md
In https://github.com/near/NEPs/pull/472 we integrated a popular linter. Here we update the existing markdown files to clean up linting issues.
- `specs`  -- let's do it in other PR, will be easier to review.
=> chore: linting neps

README.md, neps/nep-0448.md
- marks the NEP as finalised
- Adds it to the list of NEPs on the README.md
=> fix: I believe that zero-balance accounts are now finalised

README.md
* added nep-393 to the list.
* nep-141 token concept was mainly driven by my design (as documented in the past PRs), so adding myself.
=> readme: update list of token standards

neps/nep-0145.md, neps/nep-0393.md, specs/NetworkSpec/NetworkSpec.md, specs/Proposals/0005-access-keys.md, specs/RuntimeSpec/Components/BindingsSpec/TrieAPI.md, specs/RuntimeSpec/Components/RuntimeCrate.md, specs/RuntimeSpec/Fees/Fees.md, specs/RuntimeSpec/FunctionCall.md, specs/RuntimeSpec/Receipts.md, specs/Standards/StorageManagement.md
remove duplicate words to enhance readability.
=> chore: remove duplicate words

specs/DataStructures/Account.md
Addressing https://github.com/near/NEPs/pull/587#discussion_r1942423525 here because that PR was already merged.
=> docs: near-implicit nonce

README.md, neps/nep-0584.md
* Adds NEP-584 to Readme
* Removes template and updates status in NEP-584
=> chore: update readme, cleanup

.github/workflows/lint.yml
Updating changed-files dep as pre v46 is vulnerable to CVE-2025-30066 https://github.com/tj-actions/changed-files/releases
=> Update lint.yml changed-files

specs/Economics/Economic.md
minor updates to sync with the code (in `reward_calculator.rs`)
=> update the validator rewards calculation doc

specs/Standards/Appendix/README.md
=> Fix Appendix Label for 297 Events Standard
