near/NEPs

- specs/RuntimeSpec/Components/BindingsSpec/ContextAPI.md
Exposing ordinal of epoch to the runtime. Also added already implemented `block_timestamp`.
> [Spec] Expose epoch height in runtime bindings

- specs/Economics/README.md
Switch spec for economics to do state staking. See details of the proposal and discussion #40.
Fixes #40
> [Spec] Switch to state staking in economics

- specs/GenesisConfig/GenesisConfig.md
Change the fields that are percentages in genesis config to use fractions to have better flexibility.
> Use fraction in genesis config for precentages

- specs/DataStructures/Account.md
Specify that short top level accounts are allowed only by registrar account. Delaying details of the registrar spec post MainNet.
> [Spec] Top Level Accounts by Registrar

- specs/ChainSpec/README.md
- specs/ChainSpec/Upgradability.md
- specs/SUMMARY.md
This is outcome of discussions:
- https://commonwealth.im/near/proposal/discussion/261-upgradability
- https://github.com/nearprotocol/nearcore/issues/1994
- https://github.com/nearprotocol/nearcore/issues/2498
- https://near-community.slack.com/archives/C0132RCT6AC/p1589190011058000
And in short provides smooth upgrading that is defined by % of validators switching to new version and reaching consensus within an epoch on that.
> Initial spec for upgradability

- specs/Standards/Tokens/FungibleToken.md
We often call this the "NEP21" standard, but this document by itself never mentions this code name. Links directly to this document, rather than to the potentially-outdated pull request, will not reveal this shorthand.
I'm not sure it's worth linking to the original pull-request. On the one hand, it explains where the `21` comes from. On the other hand, the PR is potentially outdated. Is it worth linking to?
> refactor(nep21): link to the original PR

- specs/README.md
Very simple and straightforward. Noticed it while going through the documentation.
> Remove the extra `Economics` link in README

- specs/DataStructures/Account.md
As we actually do allow account ids of length 64 that are not hex, we should make it more clear in spec
> Fix account id specification

- specs/Standards/NonFungibleToken/Core.md
Seems like this was copied from FT equivalent
> fix(nft): typo in nft_resolve_transfer

- specs/Standards/NonFungibleToken/Core.md
Also, add Errata section and explain update
> standards/nft/core: fix approval_id type

- specs/Standards/NonFungibleToken/Core.md
Partially addresses #250
NFT was initially copy-pasted from FT and we failed to update references to `ft_*` methods in some of the comments.
> standards(nft): fix copypasta-refs to `ft_*`

- specs/Standards/NonFungibleToken/Payout.md
As discussed, this was overlooked when the NFT Payout Standard was merged. All approval IDs should be u64, not U64. Other minor changes.
We still want to rewrite this standard a bit to use TypeScript instead of Rust, but I want to get this in quick as there are projects needing it.
> NFT Payout Standard: fix approval_id from U64 to u64

- specs/Standards/NonFungibleToken/Metadata.md
Fixes #251 
This clears up unclear messaging in the original version and contains an errata section which is a good summary:
The first version (`1.0.0`) had confusing language regarding the fields:
- `issued_at`
- `expires_at`
- `starts_at`
- `updated_at`
It gave those fields the type `string|null` but it was unclear whether it should be a Unix epoch in milliseconds or [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html). Upon having to revisit this, it was determined to be the most efficient to use epoch milliseconds as it would reduce the computation on the smart contract and can be derived trivially from the block timestamp.
> Add version 2.0.0 for NFT Metadata changing time fields to be a number (Unix epoch in milliseconds)

- specs/Standards/NonFungibleToken/Event.md
We've already collected some information about NFTs in Indexer DB.
Some of the entries do not follow our standard fully: `authorized_id` is filled by ids from internal contract implementation (examples: 1, 2, 7).
I feel it's our fault; we do not communicate this part properly. I've added one more example to the doc.
Another part of the issue is to share it with the contract creators.
For now, we have only one contract that used `authorized_id` field
https://explorer.near.org/accounts/misfits.tenk.near
It's not hard to google them
https://paras.id/collection/misfits.tenk.near
Does anyone know how to contact them?
> doc(nft): add example to events with authorized_id

- specs/Standards/NonFungibleToken/Core.md
Changed the approved account IDs parameter in nft_resolve_transfer to be type Record<string, number> instead of string[]. 
Fixes #301
> NFT Resolve Transfer Approved Account Parameter Patch Fix

- specs/Standards/EventsFormat.md
Closes #297 
In the separate branches, I will rewrite NFT NEP-171 a bit and add events section to FT NEP-141 standard.
> feat(standards): add Events Format NEP

- specs/Standards/README.md
The link from the start page is missing
https://nomicon.io/Standards/README.html
> doc(standards): add link to events format nep

- specs/SUMMARY.md
That should hopefully fix 404
https://nomicon.io/Standards/EventsFormat.html
> fix: fix the link to events format nep

- specs/Standards/NonFungibleToken/ApprovalManagement.md
- specs/Standards/NonFungibleToken/Core.md
- specs/Standards/NonFungibleToken/Enumeration.md
- specs/Standards/NonFungibleToken/Event.md
- specs/Standards/NonFungibleToken/Metadata.md
- specs/Standards/NonFungibleToken/Payout.md
The navbar is pretty busy right now and hard to look at: 
I've changed it to be shorter:
> Changed navbar for nft standard to be shorter and more informative

- specs/Standards/NonFungibleToken/ApprovalManagement.md
- specs/Standards/NonFungibleToken/Core.md
- specs/Standards/NonFungibleToken/Metadata.md
The token struct field names are not consistent with current [implementations](https://github.com/near/near-sdk-rs/blob/6596dc311036fe51d94358ac8f6497ef6e5a7cfc/near-contract-standards/src/non_fungible_token/token.rs#L12) and the rust [docs](https://docs.rs/near-contract-standards/latest/near_contract_standards/non_fungible_token/struct.Token.html). I've changed the token struct field names to be consistent:
- `id` changed to `token_id`
- `approvals` changed to `approved_account_ids`
> Consistent NFT Standard Token Struct Field Names

- specs/RuntimeSpec/Fees/_category_.json
- specs/Standards/NonFungibleToken/ApprovalManagement.md
This PR fixes an issue reported by @Longarithm  where `https://nomicon.io/RuntimeSpec/Fees` was not being listed on the left-side navigation bar.
> Fix Fees.md navigation

- specs/RuntimeSpec/Scenarios/FinancialTransaction.md
The transaction validity period has been configured via genesis for
years.  Even before the date listed in the document.  Update
information on the validity period.
> Update information about transaction_validity_period

- website/docusaurus.config.js
Relevant documentation for this version of docusaurus: https://6220d0362c028b000827f851--docusaurus-2.netlify.app/docs/2.0.0-beta.15/api/themes/configuration#respectPrefersColorScheme
Sorry for not going through any specific process for this PR. It's not a Spec change so I've just committed via the UI and opened the PR.
> Respect system preference for theme in website

- specs/ChainSpec/Transactions.md
The text: _within a batch all transactions keys should have different._ does not make much sense here. I believe it should either be _within a batch all transactions keys should **be** different._ or maybe some text is missing?
> Corrected Transaction ordering text

- neps/nep-0001.md
- neps/nep-0141.md
- neps/nep-0145.md
- neps/nep-0148.md
- neps/nep-0171.md
- neps/nep-0177.md
- neps/nep-0178.md
- neps/nep-0181.md
- neps/nep-0245.md
- neps/nep-0297.md
I've noticed several urls were broken on the NEPs so I had a go at all of them This PR updates the urls  and moves them as references at the bottom of the md Files. 
This improves on DRY and will help updating them in future. 
Few questions: 
Where shall https://github.com/near/NEPs/blob/master/neps/nep-0021.md#reference-implementation url point to ?
Shall we move all mentioned urls as refs at the bottom of the page (currently the NEPs use mixed approach, this pr makes all urls pointing to local(to repository) urls as refs)?
> Update urls on NEPs

- specs/Standards/Tokens/NonFungibleToken/Metadata.md
Fixing this typo cause it's a bit confusing as it might lead to thinking that `title` prop has been renamed to `name` in new specs, but it seems to be indeed just a typo.
> Typo in TokenMetadata

- specs/DataStructures/Account.md
- specs/Standards/Wallets/BridgeWallets.md
PR #368 was merged and has references to `InjectedWallet.md`, a file that doesn't exists and is breaking the nomicon.io build.
> Fix Docusaurus build

- neps/nep-0141.md
NEP-141 came through my proposal https://github.com/near/NEPs/issues/136 as a more robust Interface for Fungible Tokens and reflection from the previous NEP-122. 
Prior to that we were discussing the pitfalls for ERC20 and a better solution that would serve NEAR ecosystem needs. See Rationale described in https://github.com/near/NEPs/issues/136. I was part of the core working group (together with Evgeny, @oysterpack, @luciotato, @mikedotexe  ) designing the NEP-141, where we hardened the NEP-136 design by analyzing the storage use cases and metadata management.
> Updating NEP-141 authors

- README.md
- neps/nep-0364.md
Efficient signature verification and hashing precompile functions
> NEP-364: Efficient signature verification host functions

- specs/RuntimeSpec/Receipts.md
`receipt_id` should be [`Receipt.receipt_id`]
> Typo fixed

- neps/nep-0001.md
I believe this document uses the term "reference implementation" to mean "draft implementation".  Given that we say that `nearcore` is the reference implementation of the protocol, this PR rewords "reference implementation" to "draft implementation" to clarify the intend.
> Clarify reference and draft implementation

- specs/Standards/Tokens/NonFungibleToken/Core.md
Thanks @jonathansampson for bringing this line to attention in #317. I believe the original PR did not fix it right, though. When Dan sends `nft_transfer_call` the expectation is that he won't lose it if his NFT is not accepted.
> fix: Fixed the example provided in the NFT Motivation section

- specs/RuntimeSpec/Transactions.md
Bullet list layout indentation doesn't seem to look nice with multi-line code snippets, especially for the last section. In this PR I propose to use subtitles instead. This also includes a couple of minor fixes such as typos and rewording of signature validation description (to avoid potential confusion that transaction is actually signed by `public_key`).
> chore: reformat transaction validation section

- neps/nep-0366.md
Some things I noticed when looking over the meta transactions spec. I have no opinion if this comes in or not, but might make this more clear.
> fix: typos and confusing wording in meta transaction spec

- specs/DataStructures/AccessKey.md
Fixed the access key docs which previously mixed up function call and full access key permissions.
> Fixed Error in Access Key Docs

- specs/Economics/Economic.md
As according to the https://github.com/near/nearcore/blob/master/nearcore/src/config.rs#L139 and the code, the actual formula and value are different
> doc: Fix gas price calculation formula and ADJ_FEE

- specs/ChainSpec/SelectingBlockProducers.md
#167 is merged but the final implementation we went for chunk-only producers actually diverged from what was described there. This PR updates the block/chunk producers section so our documentation is up to date.
> Update SelecitonBlockProducers.md to be up to date

- neps/nep-0448.md
- neps/nep-9999.md
NEP for #415. Implementation can be found in https://github.com/near/nearcore/pull/8378
> zero balance account NEP

- neps/nep-0171.md
- specs/Standards/Tokens/NonFungibleToken/Event.md
Added `contract_metadata_update` event to `Standards -> Tokens -> NonFungibleToken` as per the following discussion: https://gov.near.org/t/extending-nep-171-events-standard-to-include-contract-metadata-update-events/30384
Implementation of this new event enables 3rd party applications to listen for updates to NFT contract metadata, e.g. a new dedicated IPFS gateway (`base_uri`) and provide a consistent and higher quality experience for their users.
> add contract_metadata_update event

- README.md
- neps/nep-0455.md
NEP for Parameter Compute Costs (formerly known as Parameter Weights).
For the context, this NEP was previously named "Parameter Weights" and the idea was originally proposed in https://gov.near.org/t/proposal-gas-weights-to-fight-instability-to-due-to-undercharging/30919.
Now it's renamed into "Parameter Compute Cost" to more accurately represent the fact that it is about accounting how much compute time the parameters cost and using it to limit the chunk processing time.
> NEP-455: Parameter Compute Costs

- nep-0000-template.md
When reading a NEP, it's usually hard to start with _alternatives_ before we read the specification and the main design.
It would be more logical (and more clear) if we push the _alternatives_ section down.
Also, we don't need to call it "Rationale and Altenratives", because rationale should be clearly covered in the "Motivation" section.
> docs(template): move alternatives down

- specs/RuntimeSpec/Scenarios/FinancialTransaction.md
Fixing some typos and grammar issues that I found while reading some docs
> Minor: fix some typos and grammar

- neps/nep-0455.md
Tracks the newly introduced compute costs for protocol version 61.
(draft: the changes are still being merged in, I plan to mark this PR ready for review once the testnet release has been cut and confirmed to include the relevant compute cost values.)
> update NEP-455: storage compute costs for v61

- specs/DataStructures/Account.md
Storage rent has been superseded by storage staking a long time ago.
This commit updates the account specification accordingly.
> fix: Remove reference to storage rent

- neps/nep-0141.md
- specs/Standards/Tokens/FungibleToken/Core.md
The link to FT docs on figment.io is dead, let's replace it with an archived version of the site.
Also includes the following linter fixes in Core.md;
- remove extra indentation of lists
- add blank lines around lists
- replace emphasis with real headings
> fix: replace dead link with wayback machine link

- specs/DataStructures/Account.md
- remove unused link declarations
- surround titles and code with blank lines
- give fenced code a language (using c to format comments)
> fix: linter issues in specs/DataStructures/Account

- specs/RuntimeSpec/Actions.md
> doc: add delegate action to actions specification

- neps/nep-0366.md
While updating the specs for delegate actions, I noticed that there are two small mistakes in the error description of the NEP. Or I guess it would be more accurate to say the nearcore implementation is not compliant with the NEP.
1) `DelegateActionCantContainNestedOne` is impossible to happen because the chosen serialization format does not allow nesting in the first place.
2) The name for `DelegateActionSenderDoesNotMatchReceiver` somehow managed to get even longer in the real implementation and now spells `DelegateActionSenderDoesNotMatchTxReceiver`
I know this isn't ideal. But since this is now de-facto part of the protocol, I suggest we update the NEP to reflect it. Alternatively, we could change it in nearcore. This would be a breaking change in some primitives crates, so I tend …
> fix: inaccuracies in delegate action errors

- neps/nep-0393.md
In the [reference](https://github.com/near-ndc/i-am-human/blob/cfc92b1/contracts/registry/src/registry.rs#L362) implementation we return `bool` in the `registry.sbt_revoke_by_owner` to signal if the operation should continue or it's finished.
We forgot to push this update to the standard.
This update also makes the API consistent with `sbt_recover` and `sbt_soul_transfer`
> nep-393: add bool return to sbt_revoke_by_owner

- neps/nep-0508.md
**Status**: Approved
**Meeting Recording:**
https://bit.ly/483Wo6X
SME reviews:
Protocol Work Group voting indications (❔ | 👍 | 👎 ):
* 👍 @birchmd: https://github.com/near/NEPs/pull/508#issuecomment-1852140076
* 👍 @mfornet: (https://github.com/near/NEPs/pull/508#issuecomment-1853997035)
* 👍 @mm-near: https://github.com/near/NEPs/pull/508#issuecomment-1854894139
* 👍 @bowenwang1996: (https://github.com/near/NEPs/pull/508#issuecomment-1852778996)
> NEP-508: Resharding v2

- neps/nep-0413.md
The links to the working example were broken, this commit fixes it
> Fix: links to examples for NEP413

- neps/nep-0330.md
- specs/ChainSpec/SelectingBlockProducers.md
This update introduces build details to the contract metadata, containing necessary information about how the contract was built. This makes it possible for others to reproduce the same WASM of this contract. The idea first appeared in the [cargo-near SourceScan integration thread](https://github.com/near/cargo-near/issues/131).
This NEP extension gives developers the capability to save all the required build details, making it possible to reproduce the same WASM code in the future. This ensures greater consistency in contracts and the ability to verify source code. With the assistance of tools like SourceScan and cargo-near, the development process on NEAR becomes significantly easier.
> NEP-330 extension: Build details extension

- README.md
- neps/nep-0452.md
Make the NEP-452 present in the NEPs list.
Change its status to "final".
> NEP-452 (linkdrop): Change status to "final" + add it to README.md.

- neps/nep-0455.md
The links to "cs.github.com" are now broken as it was removed. So we replace them with the usual GitHub links.
> Fix GitHub links in nep-0455.md

- specs/DataStructures/Transaction.md
https://nomicon.io/DataStructures/Transaction is blank.  I'm adding a link to the Transactions spec page.
We also could delete this page but I'm choosing not to because:
1. There might be links to this page that would break.
2. Many chains consider a Transaction to be a core data structure - so this blank page is the first place I looked to learn about the NEAR tx format.  I think having a link here that points people in the right direction could be nice for people new to NEAR.
> Transactions.md redirect

- neps/nep-0509.md
Documenting changes to validators and describing basics of reference implementation.
> doc: validator structure change, state witness reference impl

- neps/nep-0509.md
In https://github.com/near/nearcore/pull/11582 we're increasing `combined_transactions_size_limit`, so let's update the NEP to match the implementation.
> Update documentation about combined_transactions_size_limit

- specs/ChainSpec/SelectingBlockProducers.md
* Adds a missing link that's breaking the link checker 
I've verified the contents of the previous link via [wayback machine](http://web.archive.org/web/20231204231021/https://rust-random.github.io/rand/rand/distributions/struct.WeightedIndex.html)
* Fixes lint consistency error
> fix: markdownlint, linkchecker issues

- neps/nep-0568.md
Filling in the future possibilities section - and looking for more ideas :)
> Resharding V3 - added future possibilities

- neps/nep-0568.md
Filling the specification section about flat state.
> Add flat state specs to resharding NEP

- neps/nep-0568.md
Adding State Witness section and filling some empty sections.
> Resharding V3 - state witness, implementation

- neps/nep-0568.md
This is complete except for section `Handling buffered receipts that target parent shard` which is still being discussed.
> [resharding] Add sections for receipt handling

- .markdownlint.json
- neps/nep-0178.md
- specs/ChainSpec/SelectingBlockProducers.md
- specs/Standards/Tokens/MultiToken/ApprovalManagement.md
- specs/Standards/Tokens/NonFungibleToken/ApprovalManagement.md
https://github.com/near/NEPs/actions/runs/13061179058/job/36444299126?pr=568 failed, fixing it here as it is unrelated to that PR.
Fixing dead links in old files, makes linter enforce I fix other stuff too.
> chore: fix dead links 

- specs/DataStructures/Account.md
You can no longer create a top-level account (i.e. with no `.`) even if it's longer than 32 characters.
This was changed in:
* https://github.com/near/NEPs/blob/master/neps/nep-0492.md 
* https://github.com/near/nearcore/pull/9589 
* https://github.com/near/nearcore/releases/tag/1.37.0
* Protocol version 64 (about a year ago)
> Update Account/TLA docs for NEP-492

- specs/RuntimeSpec/Transactions.md
ref: 
https://github.com/near/nearcore/blob/c49288bd29a72ab979a0a6fac261ae3f347e858d/runtime/runtime/src/verifier.rs#L158-L164
here is a matching comment fix in nearcore: https://github.com/near/nearcore/pull/13494
> fix the comment on InvalidNonce error

- neps/nep-0330.md
a working implementation according to this change is present in following prs:
1. https://github.com/near/near-sdk-rs/pull/1344 (contract sdk)
2. https://github.com/near/cargo-near/pull/323 (build tool)
3. https://github.com/near/near-verify-rs/pull/4 (lib to verify WASM reproducibility of contracts with)
4. https://github.com/near/near-verify-rs/pull/9
5. https://github.com/near/cargo-near/pull/328
6. https://github.com/near/near-verify-rs/pull/10
> [NEP-330]: add `output_wasm_path` field extension

- .github/workflows/build.yml
Maintenance update: switch all jobs to setup-node@v4 for better performance and compatibility. Pure maintenance, behavior unchanged. More details in the [v4.0.0 release](https://github.com/actions/setup-node/releases/tag/v4.0.0).
> chore(ci): upgrade setup-node to v4
